name: "dbt_cop_snowflake"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "dbt_cop_snowflake"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_cop_snowflake:
    +materialized: view # All models by default will be materialized as views
    # Config indicated by + and applies to all files under models/example/
    marts:
      +materialized: table # All models in the marts/ directory will be tables.
